multiplies = "function multipliesOf3And5(numbers) {\r\n\
	numbers[3] = numbers[1] * numbers[2];\r\n\
	var sum = 0;\r\n\
	for (var i = 0; i < 3; i++) {\r\n\
		var max = numbers[0] / numbers[i + 1];\r\n\
		max = (max % numbers[i + 1] === 0) ? max - 1 : Math.floor(max);\r\n\
		var sum1 = max * (max + 1) / 2 * numbers[i + 1];\r\n\
		sum += (i < 2) ? sum1 : -sum1;\r\n\
	}\r\n\
	return sum;\r\n\
}"

fibonacci = "function evenFibonacciSum(limit) {\r\n\
	var n1 = 1, n2 = 2, sum = 0;\r\n\
	while (n2 <= limit) {\r\n\
		if (n2 % 2 === 0) {\r\n\
			sum += n2;\r\n\
		}\r\n\
		n2 += n1;\r\n\
		n1 = n2 - n1;\r\n\
	}\r\n\
	return sum;\r\n\
}"

primes = "function largestPrimeNum(number) {\r\n\
	while (number % 2 === 0) {\r\n\
		number /= 2;\r\n\
	}\r\n\
	var max = Math.sqrt(number);\r\n\
	for (var i = 3; i <= max; i += 2) {\r\n\
		while (number % i === 0) {\r\n\
			number /= i;\r\n\
			max = Math.sqrt(number);\r\n\
		}\r\n\
	}\r\n\
	return number;\r\n\
}"

activeTab = 0;

$(document).ready(function() {
	$('li > a').on('click', function(event) {
		event.preventDefault();
		$('#logo').hide();
		$('#problem').show();
	});

	$('#prob1b').on('click', function() {
		$('#probtext').html('<h1>Multiples of 3 and 5</h1>\
		<p>If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.</p>\
		<p>Find the sum of all the multiples of 3 or 5 below 1000.</p>');
		$('#probcode').text(multiplies);
	});

	$('#prob2b').on('click', function() {
		$('#probtext').html('<h1>Even Fibonacci numbers</h1>\
		<p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. \
		By starting with 1 and 2, the first 10 terms will be:</p>\
		<p>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>\
		<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, \
		find the sum of the even-valued terms.</p>');
		$('#probcode').text(fibonacci);
	});

	$('#prob3b').on('click', function() {
		$('#probtext').html('<h1>Largest prime factor</h1>\
		<p>The prime factors of 13195 are 5, 7, 13 and 29.</p>\
		<p>What is the largest prime factor of the number 600851475143 ?</p>');
		$('#probcode').text(primes);
	});
});


/*function openProblem(number) {
	switch (number) {
		case 1:
		document.getElementById("problem1").style.display = "block";
		document.getElementById("problem2").style.display = "none";
		document.getElementById("problem3").style.display = "none";
		break;
		case 2:
		document.getElementById("problem1").style.display = "none";
		document.getElementById("problem2").style.display = "block";
		document.getElementById("problem3").style.display = "none";
		break;
		case 3:
		document.getElementById("problem1").style.display = "none";
		document.getElementById("problem2").style.display = "none";
		document.getElementById("problem3").style.display = "block";
		break;
		default:
		document.getElementById("problem1").style.display = "none";
		document.getElementById("problem2").style.display = "none";
		document.getElementById("problem3").style.display = "none";
	}
	document.getElementById("problem").style.display = "none";
}*/

/*function solveProblem(number) {
	$('#probcode1').text(fibonacci);
	var oldScr = document.getElementById("problemScript");
	var newScr = document.createElement("script");
	
	if (oldScr) {
		oldScr.parentNode.removeChild(oldScr);
	}
	
	newScr.id = "problemScript";	
	var resID, time;
	
	switch (number) {
		case 1:
		code = document.getElementById("probcode1").value + " function solve() { return " + document.getElementById("func1").value + " }";
		resID = "res1";
		time = "time1";
		break;
		case 2:
		code = document.getElementById("probcode2").value + " function solve() { return " + document.getElementById("func2").value + " }";
		resID = "res2";
		time = "time2";
		break;
		default:
		code = document.getElementById("probcode3").value + " function solve() { return " + document.getElementById("func3").value + " }";
		resID = "res3";
		time = "time3";
	}
	newScr.text = code;
	document.body.appendChild(newScr);
	var start = new Date().getTime();
	document.getElementById(resID).innerHTML = solve();
	document.getElementById(time).innerHTML = new Date().getTime() - start + " ms";
}*/